spring:
  application:
           name: card-management
  threads:
    virtual:
      enabled: true
  jpa:
    properties:
      org.hibernate.envers:
        store_data_at_delete: true
        default_schema: audit
